name: Memento CI/CD

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and run Docker Compose
        run: |
          docker compose -f docker-compose.yml up -d --build

      - name: Wait for backend to be ready
        run: |
          echo "Waiting for backend to start..."
          for i in {1..30}; do
            if curl -s http://localhost:8080/actuator/health | grep -q "UP"; then
              echo "Backend is up!"
              exit 0
            fi
            echo "Waiting ($i/30)..."
            sleep 5
          done
          echo "Backend did not start in time!"
          docker compose logs
          exit 1

      - name: List running containers
        run: docker ps -a

      - name: Stop containers
        run: docker compose down
